const PASSWORD = '00000';
const travelers = ['Edwin Lin', 'Bosco Khoo', 'Anthony Au'];
const categories = ['Food', 'Transport', 'Shopping', 'Hotel', 'Ticket', 'Snack', 'Other'];
const tripDays = ['Day 1 · Tokyo', 'Day 2 · Tokyo', 'Day 3 · Tokyo', 'Day 4 · Kamakura / Yokohama', 'Day 5 · Hakone', 'Day 6 · Yokohama', 'Departure · Yokohama / Narita'];
const places = [
  { name: 'Tokyo', jp: '東京', lat: 35.6762, lon: 139.6503 },
  { name: 'Kamakura', jp: '鎌倉', lat: 35.3192, lon: 139.5467 },
  { name: 'Hakone', jp: '箱根', lat: 35.2324, lon: 139.1069 },
  { name: 'Yokohama', jp: '横浜', lat: 35.4437, lon: 139.6380 }
];
const flights = [
  { type: 'Outbound', flight: 'UO652', date: 'Sat, Jun 6, 2026', route: 'Hong Kong → Tokyo Narita', from: 'HKG', to: 'NRT', depart: '15:10', arrive: '20:40', duration: '4h 30m' },
  { type: 'Return', flight: 'UO653', date: 'Fri, Jun 12, 2026', route: 'Tokyo Narita → Hong Kong', from: 'NRT', to: 'HKG', depart: '21:35', arrive: '01:30 +1', duration: '4h 55m' }
];
const stays = [
  { city: 'Tokyo', nights: 'First 3 nights', dates: 'Jun 6, Jun 7, Jun 8', description: 'Base for evening walks, rail access, and city exploration.' },
  { city: 'Yokohama', nights: 'Final 3 nights', dates: 'Jun 9, Jun 10, Jun 11', description: 'Base for Kamakura, Hakone, harbor nights, and final shopping.' }
];
const STORAGE = { expenses: 'japanTripPhotoExpenses', rates: 'japanTripPhotoRates', currency: 'japanTripPhotoCurrency' };
let expenses = load(STORAGE.expenses, []);
let rates = load(STORAGE.rates, { HKD: 0.052, USD: 0.0067, date: 'fallback' });
let splitWith = [...travelers];
const $ = id => document.getElementById(id);

function load(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } }
function save(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch {} }
function esc(value) { return String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function scrollToSection(id) { $(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function unlockSite() { const input = $('passwordInput'); const error = $('passwordError'); if (input?.value === PASSWORD) { sessionStorage.setItem('japanTripUnlocked', 'yes'); document.body.classList.remove('locked'); } else if (input && error) { error.textContent = 'Wrong password. Please try again.'; input.value = ''; input.focus(); } }
function yen(value) { return '¥' + Math.round(Number(value || 0)).toLocaleString('en-US'); }
function money(value, currency) { return currency === 'JPY' ? yen(value) : new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(Number(value || 0)); }
function toJPY(amount, currency) { if (currency === 'JPY') return Number(amount || 0); const rate = Number(rates[currency] || 0); return rate > 0 ? Number(amount || 0) / rate : Number(amount || 0); }
function fromJPY(amount, currency) { return currency === 'JPY' ? Number(amount || 0) : Number(amount || 0) * Number(rates[currency] || 0); }
function displayMoney(jpy) { const currency = $('displayCurrency')?.value || 'HKD'; return money(fromJPY(jpy, currency), currency); }

async function apiLoadExpenses() {
  try {
    const response = await fetch('/api/expenses', { cache: 'no-store' });
    if (!response.ok) throw new Error('API unavailable');
    const data = await response.json();
    expenses = data.expenses || [];
    save(STORAGE.expenses, expenses);
  } catch (error) {
    console.warn('Using local expenses fallback:', error);
    expenses = load(STORAGE.expenses, []);
  }
  renderSpending();
}
async function apiSaveExpense(expense) {
  const response = await fetch('/api/expenses', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(expense) });
  if (!response.ok) throw new Error('Could not save expense');
}
async function apiDeleteExpense(id) {
  const response = await fetch(`/api/expenses?id=${encodeURIComponent(id)}`, { method: 'DELETE' });
  if (!response.ok) throw new Error('Could not delete expense');
}

async function fetchLatestRates() { const status = $('rateStatus'); const now = $('rateNow'); if (status) status.textContent = 'Updating exchange rates…'; try { const response = await fetch('https://open.er-api.com/v6/latest/JPY'); if (!response.ok) throw new Error('Rate request failed'); const data = await response.json(); if (!data.rates?.HKD || !data.rates?.USD) throw new Error('Missing rate data'); rates = { HKD: Number(data.rates.HKD), USD: Number(data.rates.USD), date: data.time_last_update_utc || new Date().toUTCString() }; save(STORAGE.rates, rates); if (status) status.textContent = 'Automatic rates updated: ' + rates.date; if (now) now.textContent = `Current: ¥1 = HK$${rates.HKD.toFixed(4)} / US$${rates.USD.toFixed(4)}`; renderSpending(); } catch { if (status) status.textContent = 'Could not update automatically. Using last saved rates.'; if (now) now.textContent = `Current: ¥1 = HK$${rates.HKD.toFixed(4)} / US$${rates.USD.toFixed(4)}`; } }
function renderSelectors() { $('expenseDay').innerHTML = tripDays.map(day => `<option value="${esc(day)}">${esc(day)}</option>`).join(''); $('expensePayer').innerHTML = travelers.map(name => `<option value="${esc(name)}">${esc(name)}</option>`).join(''); $('expenseCategory').innerHTML = categories.map(category => `<option value="${esc(category)}">${esc(category)}</option>`).join(''); }
function renderSplit() { $('splitButtons').innerHTML = travelers.map(name => `<button type="button" class="split-btn ${splitWith.includes(name) ? 'active' : ''}" data-split="${esc(name)}">${splitWith.includes(name) ? '✓ ' : ''}${esc(name.split(' ')[0])}</button>`).join(''); document.querySelectorAll('[data-split]').forEach(button => button.addEventListener('click', () => toggleSplit(button.dataset.split))); }
function toggleSplit(name) { splitWith = splitWith.includes(name) ? splitWith.filter(item => item !== name) : splitWith.concat(name); renderSplit(); }
async function addExpense(event) { event.preventDefault(); const amount = Number($('expenseAmount').value); if (!amount || amount <= 0) return; const expense = { id: crypto.randomUUID ? crypto.randomUUID() : String(Date.now()), day: $('expenseDay').value, payer: $('expensePayer').value, amountJPY: toJPY(amount, $('expenseCurrency').value), originalAmount: amount, originalCurrency: $('expenseCurrency').value, category: $('expenseCategory').value, note: $('expenseNote').value || 'No note', splitWith: splitWith.length ? splitWith : [...travelers] }; try { await apiSaveExpense(expense); } catch { expenses.unshift(expense); save(STORAGE.expenses, expenses); } $('expenseAmount').value = ''; $('expenseNote').value = ''; $('expenseCurrency').value = 'JPY'; splitWith = [...travelers]; renderSplit(); await apiLoadExpenses(); }
async function deleteExpense(id) { try { await apiDeleteExpense(id); } catch { expenses = expenses.filter(expense => expense.id !== id); save(STORAGE.expenses, expenses); } await apiLoadExpenses(); }
async function clearAllExpenses() { if (!confirm('Clear all spending records?')) return; for (const expense of [...expenses]) { try { await apiDeleteExpense(expense.id); } catch {} } expenses = []; save(STORAGE.expenses, expenses); renderSpending(); }
function calculateSettlements(paid, owed) { const debtors = []; const creditors = []; travelers.forEach(name => { const balance = (paid[name] || 0) - (owed[name] || 0); if (balance < -0.5) debtors.push({ name, amount: -balance }); if (balance > 0.5) creditors.push({ name, amount: balance }); }); const settlements = []; let i = 0, j = 0; while (i < debtors.length && j < creditors.length) { const amount = Math.min(debtors[i].amount, creditors[j].amount); settlements.push({ from: debtors[i].name, to: creditors[j].name, amountJPY: amount }); debtors[i].amount -= amount; creditors[j].amount -= amount; if (debtors[i].amount <= 0.5) i++; if (creditors[j].amount <= 0.5) j++; } return settlements; }
function renderSpending() { const paid = {}; const owed = {}; travelers.forEach(name => { paid[name] = 0; owed[name] = 0; }); expenses.forEach(expense => { const amount = Number(expense.amountJPY || 0); const group = expense.splitWith?.length ? expense.splitWith : travelers; paid[expense.payer] = (paid[expense.payer] || 0) + amount; group.forEach(name => owed[name] = (owed[name] || 0) + amount / group.length); }); const total = expenses.reduce((sum, expense) => sum + Number(expense.amountJPY || 0), 0); $('totalSpent').textContent = displayMoney(total); $('totalBase').textContent = 'Base amount: ' + yen(total); $('personSummary').innerHTML = travelers.map(name => { const balance = (paid[name] || 0) - (owed[name] || 0); return `<article class="person"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><b>${esc(name)}</b><p class="soft" style="margin:5px 0 0;font-size:14px">Paid ${displayMoney(paid[name])} · Share ${displayMoney(owed[name])}</p></div><div class="right"><b class="${balance >= 0 ? 'receive' : 'pay'}">${displayMoney(Math.abs(balance))}</b><p class="soft" style="margin:3px 0 0;font-size:12px">${balance >= 0 ? 'Receive' : 'Pay'}</p></div></div></article>`; }).join(''); $('dailyTotals').innerHTML = tripDays.map(day => { const dayTotal = expenses.filter(expense => expense.day === day).reduce((sum, expense) => sum + Number(expense.amountJPY || 0), 0); return `<div class="row"><span>${esc(day)}</span><b>${displayMoney(dayTotal)}</b></div>`; }).join(''); $('expenseHistory').innerHTML = expenses.length ? expenses.map(expense => `<article class="expense"><div><b>${esc(expense.note)}</b><p>${esc(expense.day)} · ${esc(expense.category)}</p><p>Paid by ${esc(expense.payer)} · Split with ${esc((expense.splitWith || []).join(', '))}</p><p>Original: ${money(expense.originalAmount, expense.originalCurrency)} · Base: ${yen(expense.amountJPY)}</p></div><div class="right"><b>${displayMoney(expense.amountJPY)}</b><br><button class="delete" type="button" data-delete="${esc(expense.id)}">Delete</button></div></article>`).join('') : '<p class="soft">No expenses recorded yet.</p>'; document.querySelectorAll('[data-delete]').forEach(button => button.addEventListener('click', () => deleteExpense(button.dataset.delete))); const settlements = calculateSettlements(paid, owed); $('settlementPlan').innerHTML = settlements.length ? settlements.map(item => `<div class="row"><span>${esc(item.from)} pays ${esc(item.to)}</span><b>${displayMoney(item.amountJPY)}</b></div>`).join('') : '<p class="soft">Everyone is settled.</p>'; }
function exportTripData() { const blob = new Blob([JSON.stringify({ version: 7, exportedAt: new Date().toISOString(), data: { expenses, rates, displayCurrency: $('displayCurrency').value } }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `japan-trip-2026-backup-${new Date().toISOString().slice(0, 10)}.json`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }
function importTripDataFromFile(event) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = async () => { try { const backup = JSON.parse(reader.result); const data = backup.data || backup; if (!Array.isArray(data.expenses)) throw new Error('Invalid backup'); if (!confirm('Import this backup?')) return; for (const expense of data.expenses) await apiSaveExpense(expense); if (data.rates) { rates = data.rates; save(STORAGE.rates, rates); } if (data.displayCurrency) { $('displayCurrency').value = data.displayCurrency; save(STORAGE.currency, data.displayCurrency); } await apiLoadExpenses(); $('rateStatus').textContent = 'Backup imported successfully.'; } catch { alert('Could not import this file.'); } finally { event.target.value = ''; } }; reader.readAsText(file); }
function weatherEmoji(code) { if (code === 0) return '☀️'; if ([1, 2, 3].includes(code)) return '⛅'; if ([45, 48].includes(code)) return '🌫️'; if ([51, 53, 55, 56, 57, 61, 63, 65, 66, 67, 80, 81, 82].includes(code)) return '🌧️'; if ([71, 73, 75, 77, 85, 86].includes(code)) return '❄️'; if ([95, 96, 99].includes(code)) return '⛈️'; return '🌤️'; }
function weatherLabel(code) { if (code === 0) return 'Clear'; if ([1, 2, 3].includes(code)) return 'Partly cloudy'; if ([45, 48].includes(code)) return 'Fog'; if ([51, 53, 55, 56, 57].includes(code)) return 'Drizzle'; if ([61, 63, 65, 66, 67, 80, 81, 82].includes(code)) return 'Rain'; if ([71, 73, 75, 77, 85, 86].includes(code)) return 'Snow'; if ([95, 96, 99].includes(code)) return 'Thunderstorm'; return 'Forecast'; }
async function loadWeather(manual = false) { const status = $('weatherStatus'); status.textContent = manual ? 'Refreshing weather…' : 'Loading weather…'; try { const results = await Promise.all(places.map(async place => { const url = `https://api.open-meteo.com/v1/forecast?latitude=${place.lat}&longitude=${place.lon}&current=temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Asia%2FTokyo&forecast_days=3`; const response = await fetch(url); if (!response.ok) throw new Error('Weather request failed'); return { place, data: await response.json() }; })); $('weatherGrid').innerHTML = results.map(({ place, data }) => { const current = data.current || {}; const daily = data.daily || {}; return `<article class="weather-card"><div class="weather-top"><div><p class="kicker">${esc(place.jp)}</p><h3>${esc(place.name)}</h3></div><div class="weather-icon">${weatherEmoji(current.weather_code)}</div></div><div class="temp">${Math.round(current.temperature_2m ?? 0)}°</div><p class="soft">${weatherLabel(current.weather_code)} · feels ${Math.round(current.apparent_temperature ?? 0)}°C</p><div class="weather-meta"><div><b>${current.relative_humidity_2m ?? '—'}%</b><br><span class="soft">Humidity</span></div><div><b>${current.wind_speed_10m ?? '—'} km/h</b><br><span class="soft">Wind</span></div><div><b>${Math.round(daily.temperature_2m_max?.[0] ?? 0)}° / ${Math.round(daily.temperature_2m_min?.[0] ?? 0)}°</b><br><span class="soft">Today</span></div><div><b>${daily.precipitation_probability_max?.[0] ?? '—'}%</b><br><span class="soft">Rain</span></div></div></article>`; }).join(''); status.textContent = 'Updated: ' + new Date().toLocaleString('en-HK', { timeZone: 'Asia/Hong_Kong' }); } catch { status.textContent = 'Weather could not load. Please check your connection and try again.'; } }
function renderStatic() { $('flightCards').innerHTML = flights.map(flight => `<article class="detail-card"><p class="kicker">${esc(flight.type)}</p><h3>${esc(flight.flight)}</h3><p class="soft">${esc(flight.date)}</p><b>${esc(flight.route)}</b><div class="flight-times"><div><p class="temp" style="font-size:32px">${esc(flight.depart)}</p><b>${esc(flight.from)}</b></div><div class="center soft">—<br><b>${esc(flight.duration)}</b></div><div class="right"><p class="temp" style="font-size:32px">${esc(flight.arrive)}</p><b>${esc(flight.to)}</b></div></div></article>`).join(''); $('stayCards').innerHTML = stays.map(stay => `<article class="detail-card"><p class="kicker">${esc(stay.nights)}</p><h3>${esc(stay.city)}</h3><p class="soft">${esc(stay.dates)}</p><p>${esc(stay.description)}</p></article>`).join(''); }
function bindEvents() { $('unlockButton')?.addEventListener('click', unlockSite); $('passwordInput')?.addEventListener('keydown', event => { if (event.key === 'Enter') unlockSite(); }); document.querySelectorAll('[data-scroll]').forEach(button => button.addEventListener('click', () => scrollToSection(button.dataset.scroll))); $('refreshWeatherButton')?.addEventListener('click', () => loadWeather(true)); $('refreshRatesButton')?.addEventListener('click', fetchLatestRates); $('exportButton')?.addEventListener('click', exportTripData); $('backupImport')?.addEventListener('change', importTripDataFromFile); $('clearExpensesButton')?.addEventListener('click', clearAllExpenses); $('expenseForm')?.addEventListener('submit', addExpense); $('displayCurrency')?.addEventListener('change', () => { save(STORAGE.currency, $('displayCurrency').value); renderSpending(); }); }
function init() { if (sessionStorage.getItem('japanTripUnlocked') === 'yes') document.body.classList.remove('locked'); try { $('displayCurrency').value = JSON.parse(localStorage.getItem(STORAGE.currency)) || 'HKD'; } catch { $('displayCurrency').value = 'HKD'; } bindEvents(); renderSelectors(); renderSplit(); renderStatic(); renderSpending(); fetchLatestRates(); loadWeather(); apiLoadExpenses(); $('passwordInput')?.focus(); }
document.addEventListener('DOMContentLoaded', init);
